org.gradle.jvmargs=-Xmx4096M
# Identity
mod_name=Kelvin
mod_id=kelvin
mod_version=0.5.0
mod_description=A dynamic gas framework for Minecraft.
mod_license=Apache-2.0
mod_author=ThePlasticPotato, PriestOfFern
homepage=https://valkyrienskies.org/
sources=https://github.com/ValkyrienSkies/Kelvin
issue_tracker=https://github.com/ValkyrienSkies/Kelvin/issues
enabled_platforms=fabric,forge
archives_base_name=kelvin
maven_group=org.valkyrienskies
loader_platform=Common
# Dependencies
vs2_version=2.4.0+3f729b68a7
vs_core_version=1.1.0+b8f10be9b1
minecraft_version=1.21.1
architectury_version=13.0.8
fabric_loader_version=0.16.10
fabric_api_version=0.103.0+1.21.1
forge_version=1.21.1-52.1.10
forge_kotlin_version=5.4.0
kotlin_version=2.0.0
cloth_config_version=15.0.130
jei_version=19.21.0.247
# Maven publishing
vs_maven_url=
vs_maven_username=
vs_maven_password=
# For release builds
curse_api_key=
curse_project_id=
modrinth_api_key=
modrinth_project_id=
